# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursar', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bindbursar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bursar.Bursar'),
        ),
    ]
