# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_bindbursar'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7ec4'),
        ),
    ]
