# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bindbursar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bursar.Bursar'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='binduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
