# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('sale', '0006_auto_20161002_2350'),
        ('bursar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('wechatid', models.CharField(max_length=30, verbose_name='\u5fae\u4fe1\u53f7')),
                ('wechatname', models.CharField(max_length=30, verbose_name='\u5fae\u4fe1\u6635\u79f0')),
                ('phone', models.CharField(max_length=30)),
                ('startup', models.IntegerField(default=0, verbose_name='\u521d\u59cb\u8d44\u91d1')),
                ('qq', models.CharField(max_length=30)),
                ('gem', models.BooleanField(default=False, verbose_name='\u521b\u4e1a\u677f')),
                ('crude', models.BooleanField(default=False, verbose_name='\u539f\u6cb9')),
                ('create', models.DateTimeField(default=datetime.datetime(2016, 10, 3, 11, 4, 57, 732000), verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify', models.DateTimeField(default=datetime.datetime(2016, 10, 3, 11, 4, 57, 732000), verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('status', models.CharField(default=0, max_length=30, verbose_name='\u72b6\u6001')),
                ('message', models.CharField(default='', max_length=30, verbose_name='\u8bf4\u660e')),
                ('first_trade', models.DateTimeField(null=True, verbose_name='\u9996\u5355\u65f6\u95f4')),
                ('receivable', models.IntegerField(default=0, verbose_name='\u76c8\u5229\u603b\u989d')),
                ('honest', models.BooleanField(default=True, verbose_name='\u8bda\u4fe1\u5ba2\u6237')),
                ('vip', models.BooleanField(default=False, verbose_name='\u5927\u5ba2\u6237')),
                ('first_trade_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='\u9996\u7b14\u8d44\u91d1')),
                ('bursar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursar.Bursar')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
    ]
