# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0002_auto_20161003_2141'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qq',
        ),
        migrations.AddField(
            model_name='customer',
            name='qqid',
            field=models.CharField(max_length=30, null=True, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='qqname',
            field=models.CharField(max_length=30, null=True, verbose_name='QQ\u6635\u79f0'),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesqq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wxqq.Qq'),
        ),
        migrations.AddField(
            model_name='customer',
            name='saleswx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wxqq.Wx'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 3, 21, 41, 3, 958000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modify',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 3, 21, 41, 3, 958000), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wechatid',
            field=models.CharField(max_length=30, null=True, verbose_name='\u5fae\u4fe1\u53f7'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wechatname',
            field=models.CharField(max_length=30, null=True, verbose_name='\u5fae\u4fe1\u6635\u79f0'),
        ),
    ]
