# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20161004_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bursar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bursar.Bursar'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 2, 30, 38, 595000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modify',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 2, 30, 38, 595000), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
    ]
