# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 02:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20161004_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='wechatid',
            new_name='wxid',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='wechatname',
            new_name='wxname',
        ),
        migrations.AlterField(
            model_name='customer',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 2, 38, 15, 144000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modify',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 2, 38, 15, 144000), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
    ]
