# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20161004_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 11, 57, 5, 701000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modify',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 11, 57, 5, 701000), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qqid',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qqname',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='QQ\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wxid',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='\u5fae\u4fe1\u53f7'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wxname',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='\u5fae\u4fe1\u6635\u79f0'),
        ),
    ]
