# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-01 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30)),
                ('role_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u516c\u53f8')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u90e8\u95e8')),
                ('bindteacher', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7ed1\u5b9a\u8001\u5e08')),
                ('bindfinance', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7ed1\u5b9a\u8d22\u52a1')),
                ('failcount', models.IntegerField(default=-1, verbose_name='\u5931\u8d25\u6b21\u6570')),
                ('faillocktime', models.DateTimeField(null=True, verbose_name='\u5931\u8d25\u9501\u5b9a\u65f6\u95f4')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.Title')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
