# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bindfinance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bindteacher',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cid',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nick',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u771f\u5b9e\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='title',
            name='role_desc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='title',
            name='role_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u90e8\u95e8'),
        ),
    ]
