# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_auto_20161002_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='role_desc',
            field=models.CharField(max_length=30),
        ),
    ]
