# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0003_auto_20161002_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='role_desc',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
