# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super', '0006_auto_20161013_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommitHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('delta', models.IntegerField(default=0, verbose_name='\u53d8\u5316\u91cf')),
                ('total', models.IntegerField(default=0, verbose_name='\u603b\u91cf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGradeHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('delta', models.IntegerField(default=0, verbose_name='\u53d8\u5316\u91cf')),
                ('total', models.IntegerField(default=0, verbose_name='\u603b\u91cf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usergradehis',
            unique_together=set([('user', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='usercommithis',
            unique_together=set([('user', 'day')]),
        ),
    ]
