# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buycash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u8d2d\u5165\u603b\u4ef7'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buycount',
            field=models.IntegerField(default=0, verbose_name='\u8d2d\u5165\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buyprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u8d2d\u5165\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u624b\u7eed\u8d39'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 7, 21, 45, 52, 40000), verbose_name='\u6536\u6b3e\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='share',
            field=models.CharField(default='5|5', max_length=5, verbose_name='\u5206\u6210\u6bd4\u4f8b'),
        ),
    ]
