# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0006_auto_20161002_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qqid', models.CharField(max_length=30, unique=True, verbose_name='qq\u53f7')),
                ('qqname', models.CharField(max_length=30, verbose_name='qq\u6635\u79f0')),
                ('bindsale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='Wx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxid', models.CharField(max_length=30, unique=True, verbose_name='\u5fae\u4fe1\u53f7')),
                ('wxname', models.CharField(max_length=30, verbose_name='\u5fae\u4fe1\u6635\u79f0')),
                ('bindsale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
            ],
        ),
    ]
