# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0014_auto_20161010_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qq',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
    ]
