# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0025_auto_20161011_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxfriendhis',
            name='total',
            field=models.IntegerField(default=0, verbose_name='\u603b\u91cf'),
        ),
        migrations.AlterField(
            model_name='qq',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
    ]
