# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0026_auto_20161011_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='QqFriendHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True, unique=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('delta', models.IntegerField(default=0, verbose_name='\u53d8\u5316\u91cf')),
                ('total', models.IntegerField(default=0, verbose_name='\u603b\u91cf')),
            ],
        ),
        migrations.AddField(
            model_name='qq',
            name='friend',
            field=models.IntegerField(default=0, verbose_name='\u597d\u53cb\u6570'),
        ),
        migrations.AddField(
            model_name='qq',
            name='modify',
            field=models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='qq',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='qqfriendhis',
            name='qq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxqq.Qq'),
        ),
    ]
