# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0027_auto_20161011_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='qq',
            name='create',
            field=models.DateField(null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='qq',
            name='delete',
            field=models.DateField(null=True, verbose_name='\u5931\u6548\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='wx',
            name='create',
            field=models.DateField(null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='wx',
            name='delete',
            field=models.DateField(null=True, verbose_name='\u5931\u6548\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='qq',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
    ]
