# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0028_auto_20161011_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qq',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='create',
            field=models.DateField(default=datetime.date(2016, 10, 12), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='wxfriendhis',
            name='day',
            field=models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterUniqueTogether(
            name='qqfriendhis',
            unique_together=set([('qq', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='wxfriendhis',
            unique_together=set([('wx', 'day')]),
        ),
    ]
