# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0030_auto_20161012_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='wx',
            name='bindemail',
            field=models.CharField(default='', max_length=30, verbose_name='\u7ed1\u5b9a\u90ae\u4ef6'),
        ),
        migrations.AddField(
            model_name='wx',
            name='bindphone',
            field=models.CharField(default='', max_length=30, verbose_name='\u7ed1\u5b9a\u624b\u673a'),
        ),
        migrations.AddField(
            model_name='wx',
            name='bindqq',
            field=models.CharField(default='', max_length=30, verbose_name='\u7ed1\u5b9aQQ'),
        ),
        migrations.AlterField(
            model_name='qq',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
    ]
