# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0031_auto_20161012_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='qq',
            name='reason',
            field=models.CharField(default='', max_length=30, verbose_name='\u5220\u9664\u7406\u7531'),
        ),
        migrations.AddField(
            model_name='wx',
            name='reason',
            field=models.CharField(default='', max_length=30, verbose_name='\u5220\u9664\u7406\u7531'),
        ),
        migrations.AlterField(
            model_name='qq',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
    ]
