# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0032_auto_20161012_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qq',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='create',
            field=models.DateField(default=datetime.date(2016, 10, 13), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
