# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0033_auto_20161013_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='qq',
            name='password',
            field=models.CharField(default='', max_length=30, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='wx',
            name='password',
            field=models.CharField(default='', max_length=30, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='qq',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='bindsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='create',
            field=models.DateField(default=datetime.date(2016, 10, 14), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
