# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleId', models.CharField(max_length=20, unique=True, verbose_name='\u5f00\u53d1ID')),
                ('company', models.CharField(max_length=30, verbose_name='\u516c\u53f8')),
                ('department', models.CharField(max_length=30, verbose_name='\u90e8\u95e8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
