# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='user',
            new_name='binduser',
        ),
    ]
