# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20161002_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='binduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
