# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20161002_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='binduser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
