# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_sale_bindteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bindteacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
    ]
