# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20161004_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleManagerPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='\u516c\u53f8')),
                ('department', models.CharField(max_length=30, verbose_name='\u90e8\u95e8')),
                ('password', models.CharField(max_length=30, verbose_name='\u5bc6\u7801')),
            ],
        ),
    ]
