# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_salemanagerpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='group',
            field=models.CharField(default='', max_length=30, verbose_name='\u7ec4'),
        ),
    ]
