# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_sale_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bindteacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='binduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
