# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursar',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='bursar',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u90e8\u95e8'),
        ),
    ]
