# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 22:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursar', '0002_auto_20161010_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursar',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bursar',
            name='department',
        ),
        migrations.AlterField(
            model_name='bursar',
            name='binduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
